#!/bin/php

<?php

require("config.php");
require("funcs.php");

	echo("> RECONNECT\n");
	$dongle=file_get_contents($netdir.$proxy["if"].".dongle");
	$cmd="/usr/simbox/actions/reload.sh ".$dongle;
	echo($cmd."\n");
	exec($cmd);
    }
}
}

check_proxies();