#!/bin/bash

#файл DEF-кодов
DOWNFILE=$1; 
#DOWNFILE='http://www.rossvyaz.ru/docs/num/DEF-9x.html';

#рабочая папка
TMPDIR='./tmp/';
RESDIR='./res/';
#файл, где сохраним csv формат кодов
FILENAME='codes';

OPER=$2;
#OPEARTOR="";

#какой регион будем выделять
REGION=$3;
#REGION='Новосибирская область';

EXTEN=$4;
#EXTEN="test";

PRICE=$5;

LENGTH=10

#качаем и преобразуем в формат csv
cat $DOWNFILE | grep "^<tr>" | sed -e 's/<\/td>//g' -e 's/<tr>//g' -e 's/<\/tr>//g' -e 's/[\t]//g' -e 's/^<td>//g' -e 's/<td>/;/g' | iconv -c -f WINDOWS-1251 -t UTF8 | grep "$REGION" | grep "$OPER" > $TMPDIR/$FILENAME
#wget -c -q -O - $DOWNFILE | grep "^<tr>" | sed -e 's/<\/td>//g' -e 's/<tr>//g' -e 's/<\/tr>//g' -e 's/[\t]//g' -e 's/^<td>//g' -e 's/<td>/;/g' | iconv -c -f WINDOWS-1251 -t UTF8 | grep "$REGION" | grep "$OPER" > $TMPDIR/$FILENAME

#проверяем не скачали ли пустышку
check=`cat $TMPDIR/$FILENAME`
if [ "$check" == "" ]; then
exit 0
fi

#скрипт на awk генерации Dial Patterns
awk_code='
#функция определения диапазона
function ret_diap(from,to)
{
     if ((to-from)==0) return from;
     else if ((to-from)==9) return "X";
     else return "["from"-"to"]";
}
#основная функция
{
        DEF=$1;
        razm=1;
        delete out_str;
        for (i=1; i <= length($3);i++)
        {
                if ((substr($3,i,1)-substr($2,i,1))==0)
                        {
                                for (r=1; r <= razm;r++)
                                {
                                        out_str[r]=out_str[r] substr($3,i,1);
                                }

                        }
                else
                        {
                                if ((substr($3,i,1)-substr($2,i,1))==9)
                                {
                                        for (r=1; r <= razm;r++)
                                        {
                                                out_str[r]=out_str[r]"X";
                                        }

                                }
                                else
                                {
                                        if (substr($3,i,1)-substr($2,i,1)>=1 && substr($3,(i+1),1)-substr($2,(i+1),1)!=9)
                                        {
                                                count=1;
                                                init_str=out_str[1];
                                                for (j=substr($2,(i),1); j < substr($3,(i),1);j++)
                                                {
                                                        if (count==1)
                                                        {
                                                                out_str[count]=init_str j ret_diap(substr($2,(i+1),1),9);
                                                        }
                                                        else
                                                        {
                                                                out_str[count]=init_str ret_diap(j,(substr($3,(i),1)-1)) "X";
                                                                j=(substr($3,(i),1)-1);
                                                        }
                                                        count++;
                                                        if (razm<count) razm=count;
                                                }
                                                out_str[count]=init_str j ret_diap(0,substr($3,(i+1),1));
                                                i++;
                                        }
                                        else
                                        {
                                                for (r=1; r <= razm;r++)
                                                {
                                                        out_str[r]=out_str[r]"["substr($2,i,1)"-"substr($3,i,1)"]";
                                                }
                                        }
                                }
                        }
        }
        for (r in out_str)
        {
                print 7DEF out_str[r];
        }
}'

#исполняем код awk, на выходе - Dial Patterns
cat $TMPDIR/codes | awk -F ';' "$awk_code" > $TMPDIR/patterns

rm $RESDIR/zones_g/extensions_$EXTEN.conf
rm $RESDIR/zones_s/extensions_$EXTEN.conf

echo "#include \"/etc/asterisk/extensions/zones/extensions_$EXTEN.conf\"" >> $RESDIR/extensions_zones.conf

for i in `cat $TMPDIR/patterns`
do
echo "exten => _$i#.,1,Macro(makecall,$EXTEN,\${EXTEN})" >> $RESDIR/zones_g/extensions_$EXTEN.conf
echo "exten => _$i,1,Macro(makecall,$EXTEN,\${EXTEN})" >> $RESDIR/zones_s/extensions_$EXTEN.conf
echo "$i;$PRICE;$EXTEN" >> $RESDIR/price.csv
done

