#!/bin/sh
mkdir /var/svistok/firmware
mkdir /var/svistok/firmware/_1_7_3
mkdir /var/svistok/firmware/22
mkdir /var/svistok/firmware/173
mkdir /var/svistok/firmware/1550
mkdir /var/svistok/general
mkdir /var/svistok/sim
mkdir /var/svistok/sim/statistics
mkdir /var/svistok/sim/statistics/billing
mkdir /var/svistok/sim/limits
mkdir /var/svistok/sim/state
mkdir /var/svistok/sim/settings
mkdir /var/svistok/sim/log
mkdir /var/svistok/devices
mkdir /var/svistok/dongles
mkdir /var/svistok/dongles/statistics
mkdir /var/svistok/dongles/errors
mkdir /var/svistok/dongles/state
mkdir /var/svistok/dongles/settings
mkdir /var/svistok/dongles/log
mkdir /var/svistok/lists
mkdir /var/svistok/readers
mkdir /var/svistok/readers/sim
mkdir /var/svistok/readers/sim/150
mkdir /var/svistok/readers/state
mkdir /var/svistok/bs
mkdir /var/svistok/bs/statistics
mkdir /var/svistok/bs/state
mkdir /var/svistok/bs/settings
mkdir /var/svistok/other
mkdir /var/simnode
mkdir /var/simbox
mkdir /var/simbox/firmware
mkdir /var/simbox/firmware/process
mkdir /var/simbox/firmware/bin
mkdir /var/simbox/firmware/bin/173
mkdir /var/simbox/firmware/bin/1550
mkdir /var/simbox/plan.last
mkdir /var/simbox/plan
mkdir /var/simbox/sim
mkdir /var/simbox/sim/statistics
mkdir /var/simbox/sim/state
mkdir /var/simbox/sim/settings
mkdir /var/spool
mkdir /var/spool/asterisk
mkdir /var/spool/asterisk/system
mkdir /var/spool/asterisk/monitor
mkdir /var/spool/asterisk/outgoing
mkdir /var/spool/asterisk/dictate
mkdir /var/spool/asterisk/monitor.flac
mkdir /var/spool/asterisk/voicemail
mkdir /var/spool/asterisk/voicemail/default
mkdir /var/spool/asterisk/voicemail/default/1234
mkdir /var/spool/asterisk/voicemail/default/1234/en
mkdir /var/spool/asterisk/voicemail/default/1234/INBOX
mkdir /var/spool/asterisk/tmp
mkdir /var/spool/asterisk/meetme
mkdir /var/log
mkdir /var/log/asterisk
mkdir /var/log/asterisk/cdr-csv
mkdir /var/log/asterisk/cdr-custom
mkdir /var/log/asterisk/cel-custom
mkdir /var/samsebe
mkdir /var/samsebe/g729
mkdir /var/samsebe/g729/out
mkdir /var/samsebe/g729/in

chmod -R 777 /var/simbox
chmod -R 777 /var/svistok