#!/bin/sh
mkdir /mnt/disk/var/svistok/firmware
mkdir /mnt/disk/var/svistok/firmware/_1_7_3
mkdir /mnt/disk/var/svistok/firmware/22
mkdir /mnt/disk/var/svistok/firmware/173
mkdir /mnt/disk/var/svistok/firmware/1550
mkdir /mnt/disk/var/svistok/general
mkdir /mnt/disk/var/svistok/sim
mkdir /mnt/disk/var/svistok/sim/statistics
mkdir /mnt/disk/var/svistok/sim/statistics/billing
mkdir /mnt/disk/var/svistok/sim/limits
mkdir /mnt/disk/var/svistok/sim/state
mkdir /mnt/disk/var/svistok/sim/settings
mkdir /mnt/disk/var/svistok/sim/log
mkdir /mnt/disk/var/svistok/devices
mkdir /mnt/disk/var/svistok/dongles
mkdir /mnt/disk/var/svistok/dongles/statistics
mkdir /mnt/disk/var/svistok/dongles/errors
mkdir /mnt/disk/var/svistok/dongles/state
mkdir /mnt/disk/var/svistok/dongles/settings
mkdir /mnt/disk/var/svistok/dongles/log
mkdir /mnt/disk/var/svistok/lists
mkdir /mnt/disk/var/svistok/readers
mkdir /mnt/disk/var/svistok/readers/sim
mkdir /mnt/disk/var/svistok/readers/sim/150
mkdir /mnt/disk/var/svistok/readers/state
mkdir /mnt/disk/var/svistok/bs
mkdir /mnt/disk/var/svistok/bs/statistics
mkdir /mnt/disk/var/svistok/bs/state
mkdir /mnt/disk/var/svistok/bs/settings
mkdir /mnt/disk/var/svistok/other
mkdir /mnt/disk/var/simnode
mkdir /mnt/disk/var/simbox
mkdir /mnt/disk/var/simbox/firmware
mkdir /mnt/disk/var/simbox/firmware/process
mkdir /mnt/disk/var/simbox/firmware/bin
mkdir /mnt/disk/var/simbox/firmware/bin/173
mkdir /mnt/disk/var/simbox/firmware/bin/1550
mkdir /mnt/disk/var/simbox/plan.last
mkdir /mnt/disk/var/simbox/plan
mkdir /mnt/disk/var/simbox/sim
mkdir /mnt/disk/var/simbox/sim/statistics
mkdir /mnt/disk/var/simbox/sim/state
mkdir /mnt/disk/var/simbox/sim/settings
mkdir /mnt/disk/var/spool
mkdir /mnt/disk/var/spool/asterisk
mkdir /mnt/disk/var/spool/asterisk/system
mkdir /mnt/disk/var/spool/asterisk/monitor
mkdir /mnt/disk/var/spool/asterisk/outgoing
mkdir /mnt/disk/var/spool/asterisk/dictate
mkdir /mnt/disk/var/spool/asterisk/monitor.flac
mkdir /mnt/disk/var/spool/asterisk/voicemail
mkdir /mnt/disk/var/spool/asterisk/voicemail/default
mkdir /mnt/disk/var/spool/asterisk/voicemail/default/1234
mkdir /mnt/disk/var/spool/asterisk/voicemail/default/1234/en
mkdir /mnt/disk/var/spool/asterisk/voicemail/default/1234/INBOX
mkdir /mnt/disk/var/spool/asterisk/tmp
mkdir /mnt/disk/var/spool/asterisk/meetme
mkdir /mnt/disk/var/log
mkdir /mnt/disk/var/log/asterisk
mkdir /mnt/disk/var/log/asterisk/cdr-csv
mkdir /mnt/disk/var/log/asterisk/cdr-custom
mkdir /mnt/disk/var/log/asterisk/cel-custom
mkdir /mnt/disk/var/samsebe
mkdir /mnt/disk/var/samsebe/g729
mkdir /mnt/disk/var/samsebe/g729/out
mkdir /mnt/disk/var/samsebe/g729/in

chmod -R 777 /mnt/disk/var/simbox
chmod -R 777 /mnt/disk/var/svistok